# Site settings
title:          PAndrews
description:    "Academic Profile Website"
url:            "https://pandrews.github.io"

# Author
author:
  name:         Pamela Andrews
  url:          https://pandrews.github.io
  email:        pamela.andrews@unt.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
